version: "3.3"

services:
  app:
    container_name: "cv-maker"
    build:
      context: ./
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_PORT=${DB_PORT}
      - mongoURI=mongodb://mongo:27017/cv-maker
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - DATABASE_ACCESS_TOKEN_SECRET=${DATABASE_ACCESS_TOKEN_SECRET}

  mongo:
    container_name: "mongo-db"
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
