services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - database
    environment:
      - DB_URL=mongodb://cv-maker
    command: npm run start:dev
  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    # volumes:
    #   - mongodata:/data/db
    os:
      image: ubuntu
      container_name: ubuntu-os
    # networks:
    #   backend-net:
    #     driver: bridge
